# Generated by Django 3.1 on 2020-12-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
